import { generateText } from "ai"
import { openai } from "@ai-sdk/openai"

export async function analyzeResume(resumeText: string) {
  try {
    // Check if OpenAI API key is available
    if (!process.env.OPENAI_API_KEY) {
      console.warn("OpenAI API key is missing. Using mock data instead.")
      return getMockAnalysis(resumeText)
    }

    // Use the AI SDK to analyze the resume
    const { text } = await generateText({
      model: openai("gpt-4o"),
      prompt: `
        Analyze the following resume and provide detailed feedback:
        
        ${resumeText.substring(0, 8000)} // Limit text length to avoid token limits
        
        Provide a JSON response with the following structure:
        {
          "overallScore": number, // 0-100
          "atsScore": number, // 0-100
          "contentScore": number, // 0-100
          "formattingScore": number, // 0-100
          "summary": string, // Overall assessment
          "keyImprovements": string[], // 3-5 key improvements
          "contentFeedback": [
            { "title": string, "description": string, "type": "positive" | "negative" | "warning" | "info" }
          ],
          "atsFeedback": [
            { "title": string, "description": string, "type": "positive" | "negative" | "warning" | "info" }
          ],
          "formattingFeedback": [
            { "title": string, "description": string, "type": "positive" | "negative" | "warning" | "info" }
          ]
        }
      `,
      system: `
        You are an expert resume analyzer with years of experience in HR and recruiting.
        Analyze the resume thoroughly and provide constructive feedback to help the person improve.
        Focus on ATS compatibility, content quality, formatting, and overall impression.
        Be specific in your feedback and provide actionable suggestions.
        Your response must be in valid JSON format as specified in the prompt.
      `,
    })

    // Parse the JSON response
    try {
      return JSON.parse(text)
    } catch (error) {
      console.error("Error parsing AI response:", error)
      // Fall back to mock data if parsing fails
      return getMockAnalysis(resumeText)
    }
  } catch (error) {
    console.error("Error analyzing resume:", error)
    // Fall back to mock data if AI analysis fails
    return getMockAnalysis(resumeText)
  }
}

function getMockAnalysis(resumeText: string) {
  // This is a placeholder for the AI analysis
  // In a real app, this would be generated by the AI model

  // Determine if this is the "John Doe" or "Jane Smith" resume based on text content
  const isJohnDoe = resumeText.includes("John Doe")

  if (isJohnDoe) {
    return {
      overallScore: 78,
      atsScore: 82,
      contentScore: 75,
      formattingScore: 77,
      summary:
        "This is a solid software engineering resume with good technical skills and experience. It's generally ATS-friendly but could benefit from more quantifiable achievements and a clearer structure.",
      keyImprovements: [
        "Add more quantifiable achievements throughout your experience section",
        "Include specific projects or technologies you've worked with",
        "Enhance your summary with more specific technical expertise",
        "Consider adding a projects section to showcase your work",
      ],
      contentFeedback: [
        {
          title: "Strong Technical Skills",
          description:
            "Your technical skills section is comprehensive and well-organized, clearly showing your full-stack capabilities.",
          type: "positive",
        },
        {
          title: "Experience Lacks Detail",
          description:
            "While you have some good achievements listed, many of your bullet points could be more specific and include more metrics or outcomes.",
          type: "negative",
        },
        {
          title: "Education Section",
          description:
            "Your education section is concise and includes relevant coursework, which is good for a software engineering position.",
          type: "positive",
        },
        {
          title: "Missing Projects",
          description:
            "Consider adding a dedicated projects section to showcase specific applications or systems you've built.",
          type: "warning",
        },
      ],
      atsFeedback: [
        {
          title: "Good Keyword Optimization",
          description:
            "Your resume contains many relevant technical keywords that will help it pass ATS scans for software engineering roles.",
          type: "positive",
        },
        {
          title: "Simple Format",
          description: "The clean format without complex tables or graphics will help with ATS readability.",
          type: "positive",
        },
        {
          title: "Job Title Alignment",
          description: "Your job titles align well with standard industry titles, which helps with ATS matching.",
          type: "positive",
        },
        {
          title: "Contact Information",
          description:
            "Consider formatting your LinkedIn URL without the 'linkedin.com/in/' prefix for better ATS parsing.",
          type: "warning",
        },
      ],
      formattingFeedback: [
        {
          title: "Consistent Structure",
          description:
            "Your resume maintains consistent formatting throughout, which creates a professional appearance.",
          type: "positive",
        },
        {
          title: "Section Headers",
          description: "Your section headers stand out clearly, making the resume easy to scan.",
          type: "positive",
        },
        {
          title: "Bullet Point Length",
          description:
            "Some of your bullet points are too short. Aim for 1-2 lines per bullet for better readability and detail.",
          type: "warning",
        },
        {
          title: "White Space",
          description: "The resume could benefit from more white space between sections to improve readability.",
          type: "warning",
        },
      ],
    }
  } else {
    return {
      overallScore: 85,
      atsScore: 88,
      contentScore: 87,
      formattingScore: 80,
      summary:
        "This is a strong product management resume with excellent quantifiable achievements and clear demonstration of impact. The structure is clear and the content is relevant to product management roles.",
      keyImprovements: [
        "Add more details about specific methodologies or frameworks you've used",
        "Consider adding a section on notable projects or product launches",
        "Enhance your skills section with more product management tools",
        "Improve formatting consistency between sections",
      ],
      contentFeedback: [
        {
          title: "Strong Quantifiable Achievements",
          description:
            "Your resume effectively showcases your impact with specific metrics like '$2M in revenue' and '25% increase in user retention'.",
          type: "positive",
        },
        {
          title: "Clear Professional Summary",
          description:
            "Your summary effectively communicates your experience level and key strengths as a product manager.",
          type: "positive",
        },
        {
          title: "Comprehensive Experience",
          description:
            "Your work experience covers key product management responsibilities across the product lifecycle.",
          type: "positive",
        },
        {
          title: "Missing Product Details",
          description:
            "Consider adding more specific details about the products you managed, including their target market and key features.",
          type: "warning",
        },
      ],
      atsFeedback: [
        {
          title: "Excellent Keyword Optimization",
          description:
            "Your resume contains many relevant product management keywords that will help it pass ATS scans.",
          type: "positive",
        },
        {
          title: "Clear Job Titles",
          description: "Your job titles are standard and clearly indicate progression, which helps with ATS matching.",
          type: "positive",
        },
        {
          title: "Skills Section",
          description:
            "Your skills section is well-categorized, making it easy for ATS systems to identify your capabilities in different areas of product management.",
          type: "positive",
        },
        {
          title: "Education Format",
          description:
            "Consider adding more details about relevant coursework or projects in your education section to strengthen keyword matching.",
          type: "warning",
        },
      ],
      formattingFeedback: [
        {
          title: "Clear Section Organization",
          description: "Your resume has a logical flow with clearly defined sections that make it easy to navigate.",
          type: "positive",
        },
        {
          title: "Bullet Point Consistency",
          description: "Your bullet points are consistently formatted and begin with strong action verbs.",
          type: "positive",
        },
        {
          title: "Contact Information Layout",
          description:
            "Your contact information is well-organized but consider adding more space between elements for better readability.",
          type: "warning",
        },
        {
          title: "Date Formatting",
          description:
            "Ensure consistent date formatting throughout your resume. Consider using the same format (Month Year) for all dates.",
          type: "warning",
        },
      ],
    }
  }
}

